import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../..");
const dashboardTemplateRoot = path.join(repoRoot, "templates/dashboard");
const dashboardMarker = ".harness-dashboard";

export function writeJsonFile(filePath, value) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

export function copyDashboardAssets(outDir, options = {}) {
  copyDirectory(dashboardTemplateRootForLocale(options.locale), outDir);
}

export function writeDashboardDirectory(outDir, bundle, options = {}) {
  const target = path.resolve(outDir);
  assertSafeDashboardTarget(target, options);
  if (fs.existsSync(target)) fs.rmSync(target, { recursive: true, force: true });
  copyDashboardAssets(target, options);
  fs.writeFileSync(path.join(target, dashboardMarker), "generated dashboard directory\n");
  writeJsonFile(path.join(target, "data/status.json"), bundle.status);
  writeJsonFile(path.join(target, "data/tables.json"), bundle.tables);
  writeJsonFile(path.join(target, "data/documents.json"), bundle.documents);
  writeJsonFile(path.join(target, "data/graph.json"), bundle.graph);
  writeJsonFile(path.join(target, "data/adoption.json"), bundle.adoption);
  fs.writeFileSync(
    path.join(target, "assets/dashboard-data.js"),
    `window.__HARNESS_DASHBOARD__ = ${JSON.stringify(bundle, null, 2)};\n`,
  );
  fs.writeFileSync(
    path.join(target, "README.md"),
    [
      "# Harness Dashboard",
      "",
      "This is a read-only static snapshot generated by `harness dashboard --out-dir`.",
      "Open `index.html` directly in a browser. No target project files are read at browser runtime.",
      "",
    ].join("\n"),
  );
  return target;
}

export function writeDashboardFile(outFile, bundle, options = {}) {
  const target = path.resolve(outFile);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, renderDashboardFile(bundle, options));
  return target;
}

export function renderDashboardFile(bundle, options = {}) {
  const templateRoot = dashboardTemplateRootForLocale(options.locale);
  const readAsset = (relativePath) => fs.readFileSync(path.join(templateRoot, relativePath), "utf8");
  const css = readAsset("assets/app.css");
  const i18n = readAsset("assets/i18n.js");
  const markdown = readAsset("assets/markdown-reader.js");
  const mermaid = readAsset("assets/mermaid-renderer.js");
  const app = readAsset("assets/app.js");
  const title = options.locale === "zh-CN" ? "Harness 控制台" : "Harness Dashboard";
  const payload = JSON.stringify(bundle).replace(/</g, "\\u003c");
  return `<!doctype html>
<html lang="${options.locale === "zh-CN" ? "zh-CN" : "en"}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <link rel="icon" href="data:,">
  <style>${css}</style>
</head>
<body>
  <div id="app" class="app-shell" aria-live="polite"></div>
  <script>window.__HARNESS_DASHBOARD__ = ${payload};</script>
  <script>${i18n}</script>
  <script>${markdown}</script>
  <script>${mermaid}</script>
  <script>${app}</script>
</body>
</html>`;
}

function assertSafeDashboardTarget(target, options) {
  const localizedDashboardTemplateRoot = dashboardTemplateRootForLocale(options.locale);
  const protectedRoots = [
    path.parse(target).root,
    process.env.HOME,
    options.repoRoot,
    options.projectRoot,
    options.docsRoot,
    dashboardTemplateRoot,
    localizedDashboardTemplateRoot,
  ].filter(Boolean).map((item) => path.resolve(item));
  if (protectedRoots.includes(target)) {
    throw new Error(`Refusing unsafe dashboard output directory: ${target}`);
  }
  for (const root of [options.docsRoot, dashboardTemplateRoot, localizedDashboardTemplateRoot].filter(Boolean).map((item) => path.resolve(item))) {
    if (isPathInside(target, root)) {
      throw new Error(`Refusing dashboard output inside protected directory: ${target}`);
    }
  }
  if (fs.existsSync(target)) {
    const entries = fs.readdirSync(target);
    const hasMarker = fs.existsSync(path.join(target, dashboardMarker));
    if (entries.length > 0 && !hasMarker) {
      throw new Error(`Refusing to overwrite non-dashboard directory: ${target}`);
    }
  }
}

function dashboardTemplateRootForLocale(locale = "en-US") {
  const localized = locale === "zh-CN" ? path.join(repoRoot, "templates-zh-CN/dashboard") : dashboardTemplateRoot;
  return fs.existsSync(localized) ? localized : dashboardTemplateRoot;
}

function isPathInside(candidate, parent) {
  const relative = path.relative(parent, candidate);
  return Boolean(relative) && !relative.startsWith("..") && !path.isAbsolute(relative);
}

function copyDirectory(from, to) {
  if (!fs.existsSync(from)) throw new Error(`Missing dashboard template directory: ${from}`);
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const source = path.join(from, entry.name);
    const destination = path.join(to, entry.name);
    if (entry.isDirectory()) {
      copyDirectory(source, destination);
    } else {
      fs.copyFileSync(source, destination);
    }
  }
}
