import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readJsonSafe } from "./core-shared.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "../..");
const dashboardTemplateRoot = path.join(repoRoot, "templates/dashboard");
const dashboardMarker = ".harness-dashboard";

export function writeJsonFile(filePath, value) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

export function copyDashboardAssets(outDir, options = {}) {
  copyDirectory(dashboardTemplateRootForLocale(options.locale), outDir);
}

export function writeDashboardDirectory(outDir, bundle, options = {}) {
  const target = path.resolve(outDir);
  assertSafeDashboardTarget(target, options);
  if (fs.existsSync(target)) fs.rmSync(target, { recursive: true, force: true });
  fs.mkdirSync(target, { recursive: true });
  fs.writeFileSync(path.join(target, dashboardMarker), "generated dashboard directory\n");
  copyDashboardAssets(target, options);
  fs.writeFileSync(path.join(target, "assets/app.js"), readDashboardApp(dashboardTemplateRootForLocale(options.locale)));
  fs.writeFileSync(path.join(target, "index.html"), renderDashboardIndex(options.locale, options));
  writeJsonFile(path.join(target, "data/status.json"), bundle.status);
  writeJsonFile(path.join(target, "data/tables.json"), bundle.tables);
  writeJsonFile(path.join(target, "data/documents.json"), bundle.documents);
  writeJsonFile(path.join(target, "data/graph.json"), bundle.graph);
  writeJsonFile(path.join(target, "data/adoption.json"), bundle.adoption);
  writeJsonFile(path.join(target, "data/presetCatalog.json"), bundle.presetCatalog);
  fs.writeFileSync(
    path.join(target, "assets/dashboard-data.js"),
    `window.__HARNESS_DASHBOARD__ = ${JSON.stringify(bundle, null, 2)};\n`,
  );
  fs.writeFileSync(
    path.join(target, "README.md"),
    [
      "# Harness Dashboard",
      "",
      "This is a read-only static snapshot generated by `harness dashboard --out-dir`.",
      "Open `index.html` directly in a browser. No target project files are read at browser runtime.",
      "",
    ].join("\n"),
  );
  return target;
}

export function writeDashboardFile(outFile, bundle, options = {}) {
  const target = path.resolve(outFile);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, renderDashboardFile(bundle, options));
  return target;
}

export function renderDashboardFile(bundle, options = {}) {
  const templateRoot = dashboardTemplateRootForLocale(options.locale);
  const readAsset = (relativePath) => fs.readFileSync(path.join(templateRoot, relativePath), "utf8");
  const css = readAsset("assets/app.css");
  const i18n = readAsset("assets/i18n.js");
  const markdown = readAsset("assets/markdown-reader.js");
  const mermaid = readAsset("assets/mermaid-renderer.js");
  const app = readDashboardApp(templateRoot);
  const title = options.locale === "zh-CN" ? "Harness 控制台" : "Harness Dashboard";
  const payload = JSON.stringify(bundle).replace(/</g, "\\u003c");
  const runtimeLocale = options.locale === "zh-CN" ? "zh" : "en";
  return `<!doctype html>
<html lang="${options.locale === "zh-CN" ? "zh-CN" : "en"}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <link rel="icon" href="data:,">
  <style>${css}</style>
</head>
<body>
  <div id="app" class="app-shell" aria-live="polite"></div>
  <script>window.__HARNESS_DASHBOARD__ = ${payload};</script>
  <script>window.__HARNESS_LOCALE__ = ${JSON.stringify(runtimeLocale)};</script>
  <script>${i18n}</script>
  <script>${markdown}</script>
  <script>${mermaid}</script>
  <script>${app}</script>
</body>
</html>`;
}

function renderDashboardIndex(locale = "en-US", options = {}) {
  const normalizedLocale = locale === "zh-CN" ? "zh-CN" : "en";
  const runtimeLocale = locale === "zh-CN" ? "zh" : "en";
  const title = locale === "zh-CN" ? "Harness 控制台" : "Harness Dashboard";
  const assetVersion = Date.now();
  return `<!doctype html>
<html lang="${normalizedLocale}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <link rel="icon" href="data:,">
  <link rel="stylesheet" href="./assets/app.css?v=${assetVersion}">
</head>
<body>
  <div id="app" class="app-shell" aria-live="polite"></div>
  <script src="./assets/dashboard-data.js?v=${assetVersion}"></script>
  <script>window.__HARNESS_LOCALE__ = ${JSON.stringify(runtimeLocale)};</script>
  <script>window.__HARNESS_WORKBENCH__ = ${options.workbenchRuntime === true ? "true" : "false"};</script>
  <script src="./assets/i18n.js?v=${assetVersion}"></script>
  <script src="./assets/markdown-reader.js?v=${assetVersion}"></script>
  <script src="./assets/mermaid-renderer.js?v=${assetVersion}"></script>
  <script src="./assets/app.js?v=${assetVersion}"></script>
</body>
</html>`;
}

function readDashboardApp(templateRoot) {
  const manifestPath = path.join(templateRoot, "assets/app.manifest.json");
  if (!fs.existsSync(manifestPath)) return fs.readFileSync(path.join(templateRoot, "assets/app.js"), "utf8");
  const manifest = readJsonSafe(manifestPath, null);
  if (!Array.isArray(manifest) || manifest.length === 0) throw new Error(`Invalid dashboard app manifest: ${manifestPath}`);
  return `${manifest.map((relativePath) => {
    const source = path.join(templateRoot, "assets", relativePath);
    if (!fs.existsSync(source)) throw new Error(`Dashboard app source missing: ${relativePath}`);
    return fs.readFileSync(source, "utf8").trimEnd();
  }).join("\n\n")}\n`;
}

function assertSafeDashboardTarget(target, options) {
  const localizedDashboardTemplateRoot = dashboardTemplateRootForLocale(options.locale);
  const sourceRepoRoot = options.repoRoot ? path.resolve(options.repoRoot) : "";
  const projectRoot = options.projectRoot ? path.resolve(options.projectRoot) : "";
  if (
    sourceRepoRoot &&
    projectRoot &&
    isPathInside(projectRoot, sourceRepoRoot) &&
    path.basename(projectRoot) === ".harness-private" &&
    isPathInside(target, sourceRepoRoot) &&
    !isPathInside(target, projectRoot)
  ) {
    throw new Error(`Refusing private dashboard output inside publishable source package: ${target}`);
  }
  const protectedRoots = [
    path.parse(target).root,
    process.env.HOME,
    options.repoRoot,
    options.projectRoot,
    options.docsRoot,
    dashboardTemplateRoot,
    localizedDashboardTemplateRoot,
  ].filter(Boolean).map((item) => path.resolve(item));
  if (protectedRoots.includes(target)) {
    throw new Error(`Refusing unsafe dashboard output directory: ${target}`);
  }
  for (const root of [options.docsRoot, dashboardTemplateRoot, localizedDashboardTemplateRoot].filter(Boolean).map((item) => path.resolve(item))) {
    if (isPathInside(target, root)) {
      throw new Error(`Refusing dashboard output inside protected directory: ${target}`);
    }
  }
  if (fs.existsSync(target)) {
    const entries = fs.readdirSync(target);
    const hasMarker = fs.existsSync(path.join(target, dashboardMarker));
    const canRecoverGeneratedDashboard = options.recoverGeneratedDashboard === true && looksLikeGeneratedDashboardDirectory(target);
    if (entries.length > 0 && !hasMarker && !canRecoverGeneratedDashboard) {
      throw new Error(`Refusing to overwrite non-dashboard directory: ${target}`);
    }
  }
}

function looksLikeGeneratedDashboardDirectory(target) {
  const full = [
    "index.html",
    "README.md",
    "assets/app.js",
    "assets/dashboard-data.js",
    "data/status.json",
  ].every((relativePath) => fs.existsSync(path.join(target, relativePath)));
  if (full) return true;
  const readmePath = path.join(target, "README.md");
  if (!fs.existsSync(readmePath)) return false;
  try {
    const content = fs.readFileSync(readmePath, "utf8");
    return content.includes("Harness Dashboard") && content.includes("harness dashboard");
  } catch { return false; }
}

function dashboardTemplateRootForLocale(locale = "en-US") {
  return dashboardTemplateRoot;
}

function isPathInside(candidate, parent) {
  const relative = path.relative(parent, candidate);
  return Boolean(relative) && !relative.startsWith("..") && !path.isAbsolute(relative);
}

function copyDirectory(from, to) {
  if (!fs.existsSync(from)) throw new Error(`Missing dashboard template directory: ${from}`);
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const source = path.join(from, entry.name);
    const destination = path.join(to, entry.name);
    if (entry.isDirectory()) {
      copyDirectory(source, destination);
    } else {
      fs.copyFileSync(source, destination);
    }
  }
}
